---
LogConfig:
  Name: diana
  Env: dev
  Level: debug
  Duration: 24h
  HistoryPath: tmp
  FullColor: True
  FullTimestamp: True
NotifyConfig:
  Line:
    ChannelSecret: b8c89a810644c31225f141eb7313254f
    ChannelAccessToken: JkYktojuG2C6BykjnLQ6znoqOGLMq2CYaPSpgumSyaFjSrK0+Dtl6KFnpLekIW9fYXeFmq6obaLdpTrvXX735gv86OV2d61AViIEV89Q4nLkvi2DHjyDqgcttEIAvpFGPKwd+K+vbocRE0/nxOueMQdB04t89/1O/w1cDnyilFU=
GINConfig:
  Address: ":8080"
DatabaseConfig:
  Mysql:
    LogMode: false
    MaxIdle: 3
    MaxOpen: 10
    ConnMaxLifeMin: 15
    DataBases:
      Name: diana
      Address: '127.0.0.1:3306'
      Username: root
      Password: '123456'
      Database: diana
      Enable: true