name: maple currency
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  maple_currency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.3
      - name: Get maple currency
        run: |
          go mod tidy
          go run main.go