name: maple currency
on: push
jobs:
  maple_currency:
    runs-on: ubuntu-latest
    container:
      image: gfes980615/maple
    steps:
      - name: Get maple currency
        run: |
          echo "Call api"
          curl localhost:8080/diana/currency/value