name: maple currency
on: push
jobs:
  maple_currency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start service...
        run: go run main.go
      - name: Call maple API
        run: curl localhost:8080/diana/currency/value