name: maple currency
on: push
jobs:
  maple_currency:
    runs-on: ubuntu-latest
    container:
      image: gfes980615/maple
    steps:
      - name: Get maple currency
        uses: wei/curl@master
        with:
          args: http://localhost:8080/diana/currency/value